language: ruby
install: bundle install --jobs=3 --retry=3 --no-cache
cache:
  directories:
  - vendor/bundle
  - vendor/cache
  - vendor/bin
  - vendor/aws-sdk
jobs:
  stages:
  - name: Cache preparation
  - name: Check HCL style
  - name: Integration test
  - name: tag
  matrix: 
  include:
  - stage: Cache preparation
    script: "./test/travis/scripts/cache_prepare.sh"
  - stage: Check HCL style
    script: export PATH=$PATH:vendor/bin; terraform fmt
  - stage: Integration test
    script: "./test/travis/scripts/kitchen.sh"
  - stage: tag
    before_deploy:
    - git config --local user.name "pixelicous"
    - git config --local user.email "pixi@pixelabs.net"
    - git tag "$(cat version)"
    deploy:
      provider: releases
      api_key: "$GIT_TOKEN"
      file: "**/*"
      on:
        repo: pixelicous/terraform-aws-wordpress
        branch: master
notifications:
  slack:
    on_failure: always
    on_success: change
    rooms:
      secure: "rkPW175syn4mXNrxH7cmsLo9zPCnW1OBNBWx4gFMHx8qBJSmSII+7UIdtSsdbNeyrSYFpugaE8sEiD5YOL+EIWF1iUpv0v7+sqZ3ldwM6Hy1q97/uK/Gd2929QrJg0LxXUa4TZWiEfmA9trdL0Mt7TvLPhaNY3AR8xKTr7bWf9P86SXaCgBk2Zhi7WPbOS1RW96gTh3ru0voTc/w6fDN4JgVIu6uCyf5cNJMqXgbWH6ed2kPbBl4EyM59xVpPpIbiY2BuPFr2Ezv5ijsHcr2SQz48OqJfGWp/C4/N9nb+0Vui+wlmH+Bh2SywOeYWGjvNCNNzGg9vCOz2CkVoMKKoNai7wFWic+YDdC4jYKxMSYflEK1h+iqj9rJUGPxmKZxNvSxv6nDvrwamSWNP0HcbeciL3jcLVNoUBBrIi6C7NOo8PVQRA0Zph51UhcmMGktFo26WSdpxm8wRkbAS7GLEKOjlfFZ2C+VIhy5JUHrBUIrW0YB46nqKlbov+OETThgwXkRQiyaf45/tgMLNGrrPCQZGrQuqx1dMDIHOtDknUH7Yw7lkt45u0gaOt/g+Stgq0eo63r6IiAkBOnmzrSAacX9qt8RVN1p4q1/1ilSmMpYhQIS2dExzAkry9sPFK5POnb10qRqt5gWmgpPSc0IX0f6HbKvKlj3n5PKmI2IE2A="
